# Generated by Django 4.2 on 2023-04-16 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Laptop_Details", new_name="LaptopD",),
        migrations.RenameModel(old_name="Laptop_Overview", new_name="LaptopO",),
    ]
