# Generated by Django 4.2 on 2023-04-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0005_laptopo_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laptopd",
            name="accessories",
            field=models.CharField(default="No description available", max_length=255),
        ),
        migrations.AlterField(
            model_name="laptopd",
            name="clock_speed",
            field=models.CharField(default="No description available", max_length=255),
        ),
        migrations.AlterField(
            model_name="laptopd",
            name="color",
            field=models.CharField(default="No description available", max_length=255),
        ),
        migrations.AlterField(
            model_name="laptopd",
            name="expandable_memory",
            field=models.CharField(default="No description available", max_length=255),
        ),
        migrations.AlterField(
            model_name="laptopd",
            name="graphics_memory_capacity",
            field=models.CharField(default="No description available", max_length=255),
        ),
        migrations.AlterField(
            model_name="laptopd",
            name="graphics_memory_type",
            field=models.CharField(default="No description available", max_length=255),
        ),
        migrations.AlterField(
            model_name="laptopd",
            name="graphics_processor",
            field=models.CharField(default="No description available", max_length=255),
        ),
        migrations.AlterField(
            model_name="laptopd",
            name="model_number",
            field=models.CharField(default="No description available", max_length=255),
        ),
        migrations.AlterField(
            model_name="laptopd",
            name="number_of_cores",
            field=models.CharField(default="No description available", max_length=255),
        ),
        migrations.AlterField(
            model_name="laptopd",
            name="power",
            field=models.CharField(default="No description available", max_length=255),
        ),
        migrations.AlterField(
            model_name="laptopd",
            name="processor_generation",
            field=models.CharField(default="No description available", max_length=255),
        ),
        migrations.AlterField(
            model_name="laptopd",
            name="processor_name",
            field=models.CharField(default="No description available", max_length=255),
        ),
        migrations.AlterField(
            model_name="laptopd",
            name="ram",
            field=models.CharField(default="No description available", max_length=255),
        ),
        migrations.AlterField(
            model_name="laptopd",
            name="ram_type",
            field=models.CharField(default="No description available", max_length=255),
        ),
        migrations.AlterField(
            model_name="laptopd",
            name="series",
            field=models.CharField(default="No description available", max_length=255),
        ),
        migrations.AlterField(
            model_name="laptopd",
            name="ssd",
            field=models.CharField(default="No description available", max_length=255),
        ),
        migrations.AlterField(
            model_name="laptopd",
            name="ssd_capacity",
            field=models.CharField(default="No description available", max_length=255),
        ),
        migrations.AlterField(
            model_name="laptopd",
            name="suitable_for",
            field=models.CharField(default="No description available", max_length=255),
        ),
        migrations.AlterField(
            model_name="laptopd",
            name="type_of_laptop",
            field=models.CharField(default="No description available", max_length=255),
        ),
    ]
