# Generated by Django 4.2 on 2023-04-13 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Laptop_Overview",
            fields=[
                ("laptop_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("rating", models.FloatField()),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Laptop_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accessories", models.TextField()),
                ("model_number", models.CharField(max_length=255)),
                ("series", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=255)),
                ("type_of_laptop", models.CharField(max_length=255)),
                ("suitable_for", models.CharField(max_length=255)),
                ("power", models.CharField(max_length=255)),
                ("graphics_memory_type", models.CharField(max_length=255)),
                ("graphics_memory_capacity", models.CharField(max_length=255)),
                ("processor_name", models.CharField(max_length=255)),
                ("processor_generation", models.CharField(max_length=255)),
                ("ssd", models.CharField(max_length=255)),
                ("ssd_capacity", models.CharField(max_length=255)),
                ("ram", models.CharField(max_length=255)),
                ("ram_type", models.CharField(max_length=255)),
                ("clock_speed", models.CharField(max_length=255)),
                ("expandable_memory", models.CharField(max_length=255)),
                ("graphics_processor", models.CharField(max_length=255)),
                ("number_of_cores", models.CharField(max_length=255)),
                (
                    "laptop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.laptop_overview",
                    ),
                ),
            ],
        ),
    ]
