# Generated by Django 4.2 on 2023-04-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0003_alter_laptopd_accessories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laptopo", name="name", field=models.CharField(max_length=255),
        ),
    ]
