# Generated by Django 4.2 on 2023-04-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0004_alter_laptopo_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="laptopo",
            name="images",
            field=models.ImageField(default="nia.jpg", upload_to="homepage/images"),
        ),
    ]
