# Generated by Django 4.1.7 on 2023-02-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sid", models.CharField(max_length=10)),
                ("sname", models.CharField(max_length=100)),
                ("suni", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "students",
            },
        ),
    ]
