# Generated by Django 4.1.7 on 2023-04-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="laptop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sid", models.CharField(max_length=10)),
                ("sname", models.CharField(max_length=100)),
                ("suni", models.CharField(max_length=100)),
                ("l_id", models.CharField(max_length=50)),
                ("l_name", models.CharField(max_length=100)),
                ("l_rating", models.CharField(max_length=100)),
                ("l_price", models.CharField(max_length=100)),
                ("l_includes", models.CharField(max_length=100)),
                ("l_model_number", models.CharField(max_length=100)),
                ("l_series", models.CharField(max_length=100)),
                ("l_color", models.CharField(max_length=100)),
                ("l_type", models.CharField(max_length=100)),
                ("l_suitable", models.CharField(max_length=100)),
                ("l_power", models.CharField(max_length=100)),
                ("l_gm_type", models.CharField(max_length=100)),
                ("l_gm_capacity", models.CharField(max_length=100)),
                ("l_processor", models.CharField(max_length=100)),
                ("l_processor_name", models.CharField(max_length=100)),
                ("l_processor_generation", models.CharField(max_length=100)),
                ("l_ssd", models.CharField(max_length=100)),
                ("l_ssd_capacity", models.CharField(max_length=100)),
                ("l_ram", models.CharField(max_length=100)),
                ("l_ram_type", models.CharField(max_length=100)),
                ("l_clock_speed", models.CharField(max_length=100)),
                ("l_expandable_memory", models.CharField(max_length=100)),
                ("l_graphic_processor", models.CharField(max_length=100)),
                ("l_number_cores", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "laptop",
            },
        ),
        migrations.DeleteModel(
            name="student",
        ),
    ]
