# Generated by Django 4.1.7 on 2023-04-01 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0002_laptop_delete_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laptop",
            name="l_id",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="sid",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="sname",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="suni",
        ),
    ]
