# Generated by Django 4.1.7 on 2023-04-01 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0003_remove_laptop_l_id_remove_laptop_sid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laptop",
            name="l_clock_speed",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="l_color",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="l_expandable_memory",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="l_gm_capacity",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="l_gm_type",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="l_graphic_processor",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="l_includes",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="l_model_number",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="l_number_cores",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="l_power",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="l_processor",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="l_processor_generation",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="l_processor_name",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="l_ram",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="l_ram_type",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="l_series",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="l_ssd",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="l_ssd_capacity",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="l_suitable",
        ),
        migrations.RemoveField(
            model_name="laptop",
            name="l_type",
        ),
        migrations.AlterModelTable(
            name="laptop",
            table=None,
        ),
        migrations.CreateModel(
            name="d_laptop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("l_includes", models.CharField(max_length=100)),
                ("l_model_number", models.CharField(max_length=100)),
                ("l_series", models.CharField(max_length=100)),
                ("l_color", models.CharField(max_length=100)),
                ("l_type", models.CharField(max_length=100)),
                ("l_suitable", models.CharField(max_length=100)),
                ("l_power", models.CharField(max_length=100)),
                ("l_gm_type", models.CharField(max_length=100)),
                ("l_gm_capacity", models.CharField(max_length=100)),
                ("l_processor", models.CharField(max_length=100)),
                ("l_processor_name", models.CharField(max_length=100)),
                ("l_processor_generation", models.CharField(max_length=100)),
                ("l_ssd", models.CharField(max_length=100)),
                ("l_ssd_capacity", models.CharField(max_length=100)),
                ("l_ram", models.CharField(max_length=100)),
                ("l_ram_type", models.CharField(max_length=100)),
                ("l_clock_speed", models.CharField(max_length=100)),
                ("l_expandable_memory", models.CharField(max_length=100)),
                ("l_graphic_processor", models.CharField(max_length=100)),
                ("l_number_cores", models.CharField(max_length=100)),
                (
                    "l_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crudapp.laptop"
                    ),
                ),
            ],
            options={
                "db_table": "laptop",
            },
        ),
    ]
