# Generated by Django 4.1.7 on 2023-04-01 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0004_remove_laptop_l_clock_speed_remove_laptop_l_color_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="laptop",
            new_name="p_laptop",
        ),
    ]
