# Generated by Django 4.1.7 on 2023-04-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0005_rename_laptop_p_laptop"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPersonalDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uniqueId", models.CharField(blank=True, max_length=100, null=True)),
                ("dateCreated", models.DateTimeField(auto_now_add=True, null=True)),
                ("firstName", models.CharField(blank=True, max_length=100, null=True)),
                ("lastName", models.CharField(blank=True, max_length=100, null=True)),
                ("middleName", models.CharField(blank=True, max_length=250, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
