# Generated by Django 4.1.7 on 2023-04-01 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0006_userpersonaldetails"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="d_laptop",
            new_name="detailed_laptop",
        ),
    ]
