# Generated by Django 4.1.7 on 2023-04-01 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0007_rename_d_laptop_detailed_laptop"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="detailed_laptop",
            new_name="d_laptop",
        ),
        migrations.AlterModelTable(
            name="d_laptop",
            table="crudapp_d_laptop",
        ),
    ]
