# Generated by Django 4.1.7 on 2023-04-01 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0008_rename_detailed_laptop_d_laptop_alter_d_laptop_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="d_laptop",
            table="d_laptop",
        ),
        migrations.AlterModelTable(
            name="p_laptop",
            table="p_laptop",
        ),
        migrations.AlterModelTable(
            name="userpersonaldetails",
            table="user_details",
        ),
    ]
