# Generated by Django 4.1.7 on 2023-04-07 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0010_d_laptop_created_at_d_laptop_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="d_laptop",
            name="id",
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="l_Id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="crudapp.p_laptop",
            ),
        ),
    ]
