# Generated by Django 4.1.7 on 2023-04-07 04:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0011_remove_d_laptop_id_alter_d_laptop_l_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="d_laptop",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="l_Id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="crudapp.p_laptop",
            ),
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="l_clock_speed",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="l_color",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="l_expandable_memory",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="l_gm_capacity",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="l_gm_type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="l_graphic_processor",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="l_includes",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="l_model_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="l_number_cores",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="l_power",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="l_processor",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="l_processor_generation",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="l_processor_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="l_ram",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="l_ram_type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="l_series",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="l_ssd",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="l_ssd_capacity",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="l_suitable",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="l_type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="d_laptop",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
