# Generated by Django 4.1.7 on 2023-04-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0012_alter_d_laptop_created_at_alter_d_laptop_l_id_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="d_laptop",
            table="d_laptop_new",
        ),
        migrations.AlterModelTable(
            name="p_laptop",
            table="p_laptop_new",
        ),
    ]
