# Generated by Django 4.1.7 on 2023-04-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0013_alter_d_laptop_table_alter_p_laptop_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="d_laptop",
            table="d_laptop",
        ),
        migrations.AlterModelTable(
            name="p_laptop",
            table="p_laptop",
        ),
    ]
