# Generated by Django 4.1.7 on 2023-04-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0014_alter_d_laptop_table_alter_p_laptop_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="d_laptop",
            name="l_processor",
        ),
    ]
